-- drop the foreign key constraints from the annual and hourly resource tables
-- ALTER TABLE diffusion_wind.wind_resource_sm_mid_lg_near_future_turbine DROP CONSTRAINT wind_resource_sm_mid_lg_near_future_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_hourly_sm_mid_lg_near_future_turbine DROP CONSTRAINT wind_resource_hourly_sm_mid_lg_near_future_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_current_large_turbine DROP CONSTRAINT wind_resource_current_large_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_hourly_current_large_turbine DROP CONSTRAINT wind_resource_hourly_current_large_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_current_mid_size_turbine DROP CONSTRAINT wind_resource_current_mid_size_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_hourly_current_mid_size_turbine DROP CONSTRAINT wind_resource_hourly_current_mid_size_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_current_small_commercial_turbine DROP CONSTRAINT wind_resource_current_small_commercial_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_hourly_current_small_commercial_turbine DROP CONSTRAINT wind_resource_hourly_current_small_commercial_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_current_residential_turbine DROP CONSTRAINT wind_resource_current_residential_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_hourly_current_residential_turbine DROP CONSTRAINT wind_resource_hourly_current_residential_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_residential_far_future_turbine DROP CONSTRAINT wind_resource_residential_far_future_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_hourly_residential_far_future_turbine DROP CONSTRAINT wind_resource_hourly_residential_ff_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_residential_near_future_turbine DROP CONSTRAINT wind_resource_residential_near_future_turbine_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_hourly_residential_near_future_turbine DROP CONSTRAINT wind_resource_hourly_residential_nf_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_sm_mid_lg_far_future_turbine DROP CONSTRAINT wind_resource_sm_mid_lg_far_future_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_hourly_sm_mid_lg_far_future_turbine DROP CONSTRAINT wind_resource_hourly_sm_mid_lg_ff_turbine_id_fkey;

-- ALTER TABLE diffusion_wind.wind_resource_current_large_turbine DROP CONSTRAINT wind_resource_current_large_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_current_mid_size_turbine DROP CONSTRAINT wind_resource_current_mid_size_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_current_residential_turbine DROP CONSTRAINT wind_resource_current_residential_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_far_future_mid_size_and_large_turbine DROP CONSTRAINT wind_resource_far_future_mid_size_and_large_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_hourly_current_large_turbine DROP CONSTRAINT wind_resource_hourly_current_large_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_hourly_current_mid_size_turbine DROP CONSTRAINT wind_resource_hourly_current_mid_size_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_hourly_current_residential_turbine DROP CONSTRAINT wind_resource_hourly_current_residential_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_hourly_far_future_mid_size_and_large_turbine DROP CONSTRAINT wind_resource_hourly_far_future_mid_size_and_large_turbine_id_f;
-- ALTER TABLE diffusion_wind.wind_resource_hourly_near_future_mid_size_turbine DROP CONSTRAINT wind_resource_hourly_near_future_mid_size_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_hourly_near_future_residential_turbine DROP CONSTRAINT wind_resource_hourly_near_future_residential_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_near_future_mid_size_turbine DROP CONSTRAINT wind_resource_near_future_mid_size_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_near_future_residential_turbine DROP CONSTRAINT wind_resource_near_future_residential_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_current_small_commercial_turbine DROP CONSTRAINT wind_resource_current_small_commercial_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_hourly_current_small_commercial_turbine DROP CONSTRAINT wind_resource_hourly_current_small_commercial_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_hourly_far_future_small_turbine DROP CONSTRAINT wind_resource_hourly_far_future_small_turbine_id_fkey;
-- ALTER TABLE diffusion_wind.wind_resource_far_future_small_turbine DROP CONSTRAINT wind_resource_far_future_small_turbine_id_fkey;

-- create turbine id lookup table
set role 'diffusion-writers';
DROP TABLE IF EXISTS diffusion_wind.turbines;
CREATE TABLE diffusion_wind.turbines 
(
	turbine_id integer primary key,
	windpy_powercurve text unique,
	description text unique
);


\COPY diffusion_wind.turbines from '/Volumes/gispgdb.nrel.gov/data/dg_wind/updated_power_curves_descriptions.csv' with csv header;


SELECT *
FROM diffusion_wind.turbines;


-- drop the old normalize_wind_power_curves table (power curves can now be looked up directly in the windpy repo)
DROP TABLE IF EXIStS diffusion_wind.normalized_wind_power_curves;
