CREATE USER bsigrin WITH NOCREATEDB NOCREATEROLE NOCREATEUSER CONNECTION LIMIT 20 PASSWORD 'bsigrin';
CREATE USER wcole WITH NOCREATEDB NOCREATEROLE NOCREATEUSER CONNECTION LIMIT 20 PASSWORD 'wcole';
CREATE USER jduckwor WITH NOCREATEDB NOCREATEROLE NOCREATEUSER CONNECTION LIMIT 20 PASSWORD 'jduckwor';
CREATE USER mgleason WITH NOCREATEDB NOCREATEROLE NOCREATEUSER CONNECTION LIMIT 20 PASSWORD 'mgleason';
CREATE USER cdong WITH NOCREATEDB NOCREATEROLE NOCREATEUSER CONNECTION LIMIT 20 PASSWORD 'cdong';
CREATE ROLE "diffusion-writers" NOCREATEDB NOCREATEUSER NOLOGIN INHERIT NOCREATEROLE;


ALTER GROUP "diffusion-writers" ADD user bsigrin;
ALTER GROUP "diffusion-writers" ADD user wcole;
ALTER GROUP "diffusion-writers" ADD user jduckwor;
ALTER GROUP "diffusion-writers" ADD user mgleason;
ALTER GROUP "diffusion-writers" ADD user cdong;