CREATE USER bsigrin WITH NOCREATEDB NOCREATEROLE NOCREATEUSER CONNECTION LIMIT 20 PASSWORD 'bsigrin';
CREATE USER wcole WITH NOCREATEDB NOCREATEROLE NOCREATEUSER CONNECTION LIMIT 20 PASSWORD 'wcole';
CREATE USER jduckworth WITH NOCREATEDB NOCREATEROLE NOCREATEUSER CONNECTION LIMIT 20 PASSWORD 'jduckworth';
CREATE ROLE "diffusion-writers" NOCREATEDB NOCREATEUSER NOLOGIN INHERIT NOCREATEROLE;